#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/intensaobd
#    username: root
#    password: root
#  jpa:
#      hibernate:
#        ddl-auto: update
spring:
  datasource:
    url: jdbc:postgresql://ec2-54-145-102-149.compute-1.amazonaws.com:5432/d1jpgafv1ja9ut
    username: pvdymcfqxszour
    password: a9a04acaa530788ae878bfbefdad80f62fe7a587389c983f771793091c5c9c57
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rattlesnake.rmq.cloudamqp.com
    username: lmmgtdet
    password: UDlz-IlIELwOH5nLssBj6rx7JtrSWubH
    virtualhost: lmmgtdet


#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: admin