server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intensao
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: mqintensao
    port: 5672
    username: guest
    password: admin